module.exports = [
  { title: '500px', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-500px' },
  { title: 'About Me', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-aboutme' },
  { title: 'Amazon', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-amazon' },
  { title: 'Android', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-android' },
  { title: 'Angel List', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-angellist' },
  { title: 'Apple', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-apple' },
  { title: 'Behance', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-behance' },
  { title: 'Bookmate', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-bookmate' },
  { title: 'Buffer', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-buffer' },
  { title: 'Codepen', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-codepen' },
  { title: 'Coub', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-coub' },
  { title: 'Delicious', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-delicious' },
  { title: 'Deviantart', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-deviantart' },
  { title: 'Digg', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-digg' },
  { title: 'Dribbble', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-dribbble' },
  { title: 'Dropbox', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-dropbox' },
  { title: 'Ello', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-ello' },
  { title: 'Envato', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-envato' },
  { title: 'Etsy', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-etsy' },
  { title: 'Etsy Short', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-etsy-short' },
  { title: 'Evernote', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-evernote' },
  { title: 'Facebook', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-facebook' },
  { title: 'Favorite', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-favorite' },
  { title: 'Flikr', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-flikr' },
  { title: 'Foursquare', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-foursquare' },
  { title: 'GitHub', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-github' },
  { title: 'Google Drive', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-googledrive' },
  { title: 'Google Play', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-googleplay' },
  { title: 'Habrahabr', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-habrahabr' },
  { title: 'Instagram', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-instagram' },
  { title: 'JSFiddle', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-jsfiddle' },
  { title: 'Kickstarter', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-kickstarter' },
  { title: 'Like', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-like' },
  { title: 'Line Icon', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-line-icon' },
  { title: 'Line', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-line' },
  { title: 'LinkedIn', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-linkedin' },
  { title: 'LiveJournal', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-livejournal' },
  { title: 'Mail', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-mail' },
  { title: 'Map', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-map' },
  { title: 'Medium', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-medium' },
  { title: 'Messenger', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-messenger' },
  { title: 'OK', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-ok' },
  { title: 'Periscope', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-periscope' },
  { title: 'Phone', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-phone' },
  { title: 'Photobucket', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-photobucket' },
  { title: 'Pinterest', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-pinterest' },
  { title: 'Pinterest Light', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-pinterest-light' },
  { title: 'Pocket', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-pocket' },
  { title: 'Producthunt', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-producthunt' },
  { title: 'Quora', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-quora' },
  { title: 'Reddit Light', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-reddit-light' },
  { title: 'Reddit', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-reddit' },
  { title: 'RSS', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-rss' },
  { title: 'Send Light', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-send-light' },
  { title: 'Send', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-send' },
  { title: 'Shopify', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-shopify' },
  { title: 'Sketch', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-sketch' },
  { title: 'Skype', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-skype' },
  { title: 'Slack', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-slack' },
  { title: 'Slideshare', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-slideshare' },
  { title: 'Snapchat', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-snapchat' },
  { title: 'Stack Overflow', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-stackoverflow' },
  { title: 'StumbleUpon', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-stumbleupon' },
  { title: 'Swarm', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-swarm' },
  { title: 'Tripadvisor', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-tripadvisor' },
  { title: 'Tumblr', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-tumblr' },
  { title: 'Twitter', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-twitter' },
  { title: 'Upwork', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-upwork' },
  { title: 'Viadeo', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-viadeo' },
  { title: 'Vimeo', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-vimeo' },
  { title: 'VK', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-vk' },
  { title: 'VSCO grid', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-vscogrid' },
  { title: 'Web', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-web' },
  { title: 'Windows', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-windows' },
  { title: 'Wordpress', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-wordpress' },
  { title: 'Xing', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-xing' },
  { title: 'Yelp', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-yelp' },
  { title: 'YouTube', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-youtube' },
  { title: 'YouTube Play', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-youtube-play' },
  { title: 'Mywed', id: 'vcv-ui-icon-socialicons vcv-ui-icon-socialicons-mywed' }
]
